intro: A sample generator

params:
  name:
    prompt: Name your project
    type: text
    default: project

  spec: 
    prompt: Include RSpec files?
    type: yesno
    default: y

  console:
    prompt: Select console
    type: select
    list: [irb, pry]

  license: 
    prompt: Name of license file
    type: text
    default: MIT